### ISSUE TITLE
Index citation-count and reference-count operations not working with OMID

### ISSUE THREAD

**Issue by eliarizzetto** [opencitations/api#11]
Two of Index API operations, namely `citation-count/{id}` and `reference-count/{id}`, do not seem to work if an OMID is passed as parameter. Nonetheless, the operations seem to return the correct results if receiving a DOI or a PMID. 
For example, to retrieve the number of publications that cite the journal article with omid:br/062601736035, doi:10.3390/jcm11133640, and pmid:35806926, the following requests should all return the same results:

- passing a PMID: https://opencitations.net/index/api/v2/citation-count/pmid:35806926
- passing a DOI: https://opencitations.net/index/api/v2/citation-count/doi:10.3390/jcm11133640
- passing an OMID: https://opencitations.net/index/api/v2/citation-count/omid:br/062601736035

Instead only the requests using DOI and PMID return the correct citation count( i.e., in this case, `[{count: "1"}]`), while the request using OMID returns an empty list.

**Comment by ivanhb** [comment]
Fixed. This was a small issue in the _indexapi_v2.py_ module.
