### ISSUE TITLE
[bug] OC Meta API: venue's OMID not shown in result for venues with no external ID

### ISSUE THREAD

**Issue by eliarizzetto** [opencitations/api#15]
When using the `metadata` operation of the OpenCitations Meta API to retrieve a publication's metadata, the OMID of the venue is not shown in the result. This incorrect behaviour seems to be limited to cases where the venue of the searched publication does not have external identifiers registered in Meta.
For example, the call https://opencitations.net/meta/api/v1/metadata/omid:br/061903571196 returns the following result (notice the absence of the OMID in the _venue_ field):

```json
[
    {
        "author": "A Dosi, Ravi [omid:ra/061909585847]; Agrawal, Ankur [omid:ra/061909585849]; Jaiswal, Neha [omid:ra/061909585850]; Patidar, Ravindra [omid:ra/061909585851]; Shivhare, Shailendra [omid:ra/061909585848]",
        "issue": "",
        "editor": "",
        "pub_date": "2022-09-15",
        "title": "Lung Cavitation: An Unwanted Complication Of Covid-19 Lung Disease",
        "volume": "",
        "page": "31-33",
        "id": "doi:10.36106/gjra/9300981 openalex:W4306682982 omid:br/061903571196",
        "publisher": "World Wide Journals [crossref:21849 omid:ra/0640115418]",
        "type": "journal article",
        "venue": "Global Journal For Research Analysis"
    }
]
```
Below are similar examples, where the venue containing the publication passed as parameter of the call has no external IDs. Contrarily to their venue, all the BRs passed as parameters of the call (first column) have at least one external ID.

| **API call for the BR** | **Venue of the BR (retrieved via SPARQL)** |
| --- | --- |
| https://opencitations.net/meta/api/v1/metadata/omid:br/06270341222 | https://w3id.org/oc/meta/br/06270341716 |
| https://opencitations.net/meta/api/v1/metadata/omid:br/06303574208 | https://w3id.org/oc/meta/br/062303812771 |
| https://opencitations.net/meta/api/v1/metadata/omid:br/062103789879 | https://w3id.org/oc/meta/br/062103790912 |
| https://opencitations.net/meta/api/v1/metadata/omid:br/062103789843 | https://w3id.org/oc/meta/br/062103790876 |
| https://opencitations.net/meta/api/v1/metadata/omid:br/06104248116 | https://w3id.org/oc/meta/br/06104249083 |
| https://opencitations.net/meta/api/v1/metadata/omid:br/06104248265 | https://w3id.org/oc/meta/br/06104249274 |
| https://opencitations.net/meta/api/v1/metadata/omid:br/061903571196 | https://w3id.org/oc/meta/br/061903571793 |
| https://opencitations.net/meta/api/v1/metadata/omid:br/061703288139 | https://w3id.org/oc/meta/br/062303812022 |
| https://opencitations.net/meta/api/v1/metadata/omid:br/062202459452 | https://w3id.org/oc/meta/br/062202460434 |
| https://opencitations.net/meta/api/v1/metadata/omid:br/062303811888 | https://w3id.org/oc/meta/br/062303812603 |

**Comment by arcangelo7** [comment]
The issue has been resolved. We've modified the SPARQL query to always include the venue OMID in the results when available, regardless of whether the venue has other external identifiers.

The solution has been implemented and can be found in this commit:
https://github.com/opencitations/api/commit/b794741ce37a27c4457244c157b7059b8faed5b6
