### ISSUE TITLE
COCI - 520 Web Server Returned an Unknown Error

### ISSUE THREAD

**Issue by arcangelo7** [opencitations/api#4]
I believe there is an unhandled exception inside the server: when metadata are requested for a resource not present in the database, the status code is 520, instead of 404, and immediately after it's 521.
I will give you an example with the following resource: Wilcoxon, F. (1945). Individual Comparisons by Ranking Methods. Biometrics Bulletin, 1 (6), 80-83. doi: 10.2307 / 3001968.
There is no problem when asking for the references, the status code is 200 and the output is an empty list: https://w3id.org/oc/index/coci/api/v1/references/10.2307/3001968.
However, if I try requesting the metadata for the same resource, the status code is 520: `https://w3id.org/oc/index/coci/api/v1/metadata/10.2307/3001968`.
Not only that, if I try to ask again for references immediately afterwards, the status code is 521 Web Server Is Down, as if the server was restarting after an unexpected error.

**Comment by essepuntato** [comment]
Fixed, now should work correctly

**Comment by arcangelo7** [comment]
I tried to request the metadata of about 45'000 other DOI and the problem no longer occurred. Therefore, I can confirm that the bug has been fixed and I can close the issue.
