### ISSUE TITLE
Author order scrambling stops opencitations data reusability

### ISSUE THREAD

**Issue by AshtonSBradley** [opencitations/api#8]
there seems to be some randomness to author order returning in metadata.

This seems to occur extremely commonly. 

To give a typical example of what goes wrong, the article

P. B. Blakie, A. S. Bradley, M. J. Davis, R. J. Ballagh, and C. W. Gardiner, Dynamics and Statistical Mechanics of Ultra-Cold Bose Gases Using c-Field Techniques, Advances in Physics 57, 363 (2008).

appears as follows in metadata, with incorrect author order:

Author: Bradley, A S [orcid:0000-0002-3027-3195 meta:ra/062029837]; Davis, M J [orcid:0000-0001-8337-0784 meta:ra/062029838]; Blakie, P. Blair [orcid:0000-0003-4772-6514 meta:ra/0618034720]; Ballagh, R.J. [meta:ra/062306689032]; Gardiner, C.W. [meta:ra/062306689033]

see e.g. https://opencitations.net/index/search?text=10.1080%2F00018730802564254

This means attempts to use the opencitations metadata to format references is unreliable:

https://github.com/hellemo/ShortCodes.jl/issues/19

**Comment by arcangelo7** [comment]
Thank you for reporting this. There was a bug in the API, which has now been fixed
